" Load vim-plug
if empty(glob("~/.vim/autoload/plug.vim"))
    execute '!curl -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim'
endif

call plug#begin('~/.vim/plugged')

" System Plugins
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" Search
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'mileszs/ack.vim'         "ack (search, tries to use ag by default)
" Plug 'ctrlpvim/ctrlp.vim'      "ctrlp

" System information
Plug 'vim-airline/vim-airline' "airline
Plug 'tpope/vim-eunuch'        "eunuch (filesystem commands)
Plug 'tpope/vim-fugitive'      "fugitive (git)

" Vim improvements
Plug 'scrooloose/nerdtree'     "NERDTree
Plug 'tpope/vim-repeat'        "Repeat (enables . for plugins)
Plug 'kshenoy/vim-signature'   "Display marks in the gutter

" Coding plugins
Plug 'jiangmiao/auto-pairs'    "AutoPairs
Plug 'tpope/vim-commentary'    "Commentary (quick commenting)
Plug 'tpope/vim-endwise'       "Endwise
Plug 'tpope/vim-surround'      "Surround (quotes and brackets)
Plug 'brooth/far.vim'          "Find and Replace
Plug 'ludovicchabant/vim-gutentags'

"Snippets
"Plug 'SirVer/UltiSnips'        "Snippet support

" Syntax Specific Plugins
"" Ruby/Rails
Plug 'tpope/vim-rails'
Plug 'vim-ruby/vim-ruby'

"" SQL
Plug 'aliou/sql-heredoc.vim'   "SQL highlighting via heredoc (<<SQL)

"" JavaScript
Plug 'heavenshell/vim-jsdoc'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'valloric/MatchTagAlways'

"" Go
Plug 'fatih/vim-go'

"" PHP
Plug 'tobyS/vmustache'
Plug 'tobyS/pdv'

"Asctetic Plugins
Plug 'morhetz/gruvbox'
'
" Presentation Plugins
Plug 'custompro98/vim-reveal'

call plug#end()            " required

" PlugInstall
" PlugUpdate
" PlugClean
" PlugUpgrae
" PlugStatus
" PlugDif
" PlugSnapshot[!] [output path]

let mapleader = ","

" Put your non-Plugin stuff after this line
runtime! init/**.vim
