set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
" Vundle
Plugin 'VundleVim/Vundle.vim'

" System Plugins
Plugin 'mileszs/ack.vim'         "ack (search, tries to use ag by default)
Plugin 'vim-airline/vim-airline' "airline
Plugin 'ctrlpvim/ctrlp.vim'      "ctrlp
Plugin 'tpope/vim-eunuch'        "eunuch (filesystem commands)
Plugin 'tpope/vim-fugitive'      "fugitive (git)
Plugin 'scrooloose/nerdtree'     "NERDTree
Plugin 'tpope/vim-repeat'        "Repeat (enables . for plugins)
Plugin 'kshenoy/vim-signature'   "Display marks in the gutter

" Coding plugins
Plugin 'jiangmiao/auto-pairs'    "AutoPairs
Plugin 'tpope/vim-commentary'    "Commentary (quick commenting)
Plugin 'tpope/vim-endwise'       "Endwise
Plugin 'tpope/vim-surround'      "Surround (quotes and brackets)

"Snippets
Plugin 'SirVer/UltiSnips'        "Snippet support

" Syntax Specific Plugins
"" Ruby/Rails
Plugin 'tpope/vim-rails'
Plugin 'vim-ruby/vim-ruby'
Plugin 'slim-template/vim-slim'
Plugin 'elixir-editors/vim-elixir'
Plugin 'ElmCast/elm-vim'

"" SQL
Plugin 'aliou/sql-heredoc.vim'   "SQL highlighting via heredoc (<<SQL)

"" JavaScript
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'valloric/MatchTagAlways'

" Asctetic Plugins
Plugin 'ayu-theme/ayu-vim'
Plugin 'vim-airline/vim-airline-themes'

" Presentation Plugins
Plugin 'blindFS/vim-reveal'

call vundle#end()            " required

filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

syntax on
filetype plugin indent on

runtime! init/**.vim
