" Load vim-plug
if empty(glob("~/.vim/autoload/plug.vim"))
    execute '!curl -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim'
endif

" Find out what OS we're on early  (Linux|Darwin)
let g:uname = system("echo -n \"$(uname)\"")

" Must map leader before any other configs
let mapleader = ";"

" Shared utility functions
function! OpenWindow(position, height, cmd)
  execute a:position . a:height . a:cmd
endfunction

" Source plugins
function! s:SourceConfigFilesIn(directory)
  let directory_splat = '~/.vim/' . a:directory . '/*'
  for config_file in split(glob(directory_splat), '\n')
    if filereadable(config_file)
      execute 'source' config_file
    endif
  endfor
endfunction

call plug#begin('~/.vim/plugged')
call s:SourceConfigFilesIn('rcplugin')
call plug#end()

" PlugInstall
" PlugUpdate
" PlugClean
" PlugUpgrae
" PlugStatus
" PlugDif
" PlugSnapshot[!] [output path]


" Non plugin configuration goes here
call s:SourceConfigFilesIn('rcfiles')
